services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: realestate-api
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s

  ui:
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
    container_name: realestate-ui
    environment:
      - API_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_healthy
