version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: realestate-api
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
    container_name: realestate-ui
    environment:
      - API_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
